# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================


# Modified by : iamgroot42

"""Simple image classification with Inception.

Run image classification with Inception trained on ImageNet 2012 Challenge data
set.

"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from pymongo import MongoClient
from os.path import abspath

import re
import os
import json
import numpy as np
import tensorflow as tf

path_to = abspath(__file__ + "/..")

# classify_image_graph_def.pb:
#   Binary representation of the GraphDef protocol buffer.
# imagenet_synset_to_human_label_map.txt:
#   Map from synset ID to a human readable string.
# imagenet_2012_challenge_label_map_proto.pbtxt:
#   Text representation of a protocol buffer mapping a label to synset ID.


class NodeLookup(object):
  """Converts integer node ID's to human readable labels."""

  def __init__(self, uid_lookup_path = None):
    if not uid_lookup_path:
      uid_lookup_path = path_to + '/labels.txt'
    self.node_lookup = self.load(uid_lookup_path)

  def load(self, uid_lookup_path):
    """Loads a human readable English name for each softmax node.

    Args:
      uid_lookup_path: string UID to human-readable string.

    Returns:
      dict from integer node ID to human-readable string.
    """
    if not tf.gfile.Exists(uid_lookup_path):
      tf.logging.fatal('File does not exist %s', uid_lookup_path)

    proto_as_ascii_lines = tf.gfile.GFile(uid_lookup_path).readlines()
    uid_to_human = {}
    uid = 1
    for line in proto_as_ascii_lines:
      uid_to_human[uid] = line.split('\n')[0]
      uid += 1

    return uid_to_human

  def id_to_string(self, node_id):
    if node_id not in self.node_lookup:
      return ''
    return self.node_lookup[node_id]


def create_graph():
  """Creates a graph from saved GraphDef file and returns a saver."""
  with tf.gfile.FastGFile(path_to + '/graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    _ = tf.import_graph_def(graph_def, name='')


def run_inference_on_images(path, num_top_predictions = 3, db_name = "analysis", collection_name = "tags"):
  """Runs inference on every image in given path.

  Args:
    image: Path to directory containing images.
    densecap_json: Path to .json containing tags generated by densecap
    num_top_predictions: Number of top predictions to be picked

  Returns:
    True, after all data has been pushed to DB
  """
  # Creates graph from saved GraphDef.
  create_graph()
  
  # Prepare mongoDB for storing tags.
  client = MongoClient('mongodb://localhost:27017/')
  db = client[db_name]
  table = db[collection_name]

  with tf.Session() as sess:
    # Some useful tensors:
    # 'softmax:0': A tensor containing the normalized prediction across
    #   1000 labels.
    # 'pool_3:0': A tensor containing the next-to-last layer containing 2048
    #   float description of the image.
    # 'DecodeJpeg/contents:0': A tensor containing a string providing JPEG
    #   encoding of the image.
    # Runs the softmax tensor by feeding the image_data as input to the graph.
    softmax_tensor = sess.graph.get_tensor_by_name('final_result:0')

    for image in os.listdir(path):
      image_data = tf.gfile.FastGFile(path + "/" + image, 'rb').read()

      predictions = sess.run(softmax_tensor,
                           {'DecodeJpeg/contents:0': image_data})
      predictions = np.squeeze(predictions)
        # Creates node ID --> English string lookup.
      node_lookup = NodeLookup()

      top_k = predictions.argsort()[-num_top_predictions:][::-1]

      tags = {}

      for node_id in top_k:
        human_string = node_lookup.id_to_string(node_id)
        score = predictions[node_id]
        tags[human_string] = score

      # Picking top confidence value.
      tag = sorted(tags, key = tags.get, reverse = True)[0]
      confidence = float(tags[tag])
      # confidence = [ float(tags[c]) for c in tag]

      # Push to DB
      table.insert_one( { "filename": image, "tensorflow_tag": tag, "tensorflow_confidence": confidence} )

    return True


if __name__ == "__main__":
  run_inference_on_images(abspath("Images"),db_name="potato",collection_name="flowers")
